language: node_js
node_js:
  - "node"
  - "8"
  - "7"
deploy:
  provider: npm
  email: imhugofonseca@gmail.com
  api_key: $NPM_TOKEN
  tag: next
  on:
    repo: hugo-fonseca/portuguese-utils
    branch: master
    node: "node"
