language: node_js
node_js:
  - "node"
  - "8"
  - "7"
before_deploy: npm i
deploy:
  provider: npm
  email: imhugofonseca@gmail.com
  api_key: 
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: hugo-fonseca/portuguese-utils
    branch: master
    node: "node"
